version: "3"

services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "3006:3000"
    command: yarn run start
    volumes:
      - /usr/src/app/
      - /usr/src/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: challenge
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      bash -c "
        /usr/bin/pg_ctlcluster 15 main start &&
        /usr/bin/psql -U admin -d postgres -c 'CREATE DATABASE challenge;' &&
        /usr/bin/pg_ctlcluster 15 main stop
      "

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3008:80"
    depends_on:
      - postgres
